# Generated by Django 5.2.5 on 2025-09-02 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_orderupdate_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdate',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='shop.order'),
        ),
    ]
